version: "3.8"

services:
  # Serviço de backend
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHON_SERVICE_URL=http://python-service:5000
    depends_on:
      - python-service
    restart: always

  # Serviço de frontend
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${RAILWAY_PUBLIC_DOMAIN_BACKEND}
    depends_on:
      - backend
    restart: always

  # Serviço Python
  python-service:
    build:
      context: .
      dockerfile: .docker/python-service/Dockerfile
    ports:
      - "5000:5000"
    restart: always
